main = ".worker-next/index.mjs"
name = "sadaqahmadeeasy"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[assets]
directory = ".worker-next/assets"
binding = "ASSETS"
